# Generated by Django 2.1.2 on 2018-10-20 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='version',
            field=models.IntegerField(default=0),
        ),
    ]
