# Generated by Django 2.1.2 on 2018-10-21 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_auction_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='currency',
            field=models.CharField(default='EUR', max_length=5),
        ),
    ]
