# Generated by Django 2.1.2 on 2018-10-21 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_currencyrate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CurrencyRate',
        ),
    ]
