# Generated by Django 2.1.2 on 2018-10-21 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0005_delete_currencyrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='priceUSD',
            field=models.FloatField(default=0),
        ),
    ]
