# Generated by Django 2.1.2 on 2018-10-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0006_auction_priceusd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='priceUSD',
            new_name='highestBidUSD',
        ),
        migrations.AddField(
            model_name='auction',
            name='minPriceUSD',
            field=models.FloatField(default=0),
        ),
    ]
