# Generated by Django 2.1.2 on 2018-10-21 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0007_auto_20181021_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='currency',
        ),
    ]
